site_name: 'k8s'
site_description: 'Main documentation for Backstage features and platform APIs'
repo_url: https://github.com/kales5078/k8s
edit_uri: edit/main/docs

plugins:
  - techdocs-core

nav:
  - Getting Started:
      - Getting Started: 'docs/index.md'
